# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/design_fft_axi_smc_0.xci
# IP: The module: 'design_fft_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/bd_18ef.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_0/bd_18ef_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_1/bd_18ef_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_2/bd_18ef_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_3/bd_18ef_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_4/bd_18ef_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_5/bd_18ef_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_6/bd_18ef_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_7/bd_18ef_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_8/bd_18ef_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_9/bd_18ef_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_10/bd_18ef_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_11/bd_18ef_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_12/bd_18ef_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_13/bd_18ef_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_14/bd_18ef_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_15/bd_18ef_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_16/bd_18ef_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_17/bd_18ef_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_18/bd_18ef_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_19/bd_18ef_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_20/bd_18ef_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_21/bd_18ef_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_22/bd_18ef_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_23/bd_18ef_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_24/bd_18ef_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_25/bd_18ef_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_26/bd_18ef_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fft_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_1/bd_18ef_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_1/bd_18ef_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_2/bd_18ef_arsw_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_3/bd_18ef_rsw_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_4/bd_18ef_awsw_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_5/bd_18ef_wsw_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_6/bd_18ef_bsw_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_10/bd_18ef_s00a2s_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_11/bd_18ef_sarn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_12/bd_18ef_srn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_16/bd_18ef_s01a2s_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_17/bd_18ef_sawn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_18/bd_18ef_swn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_19/bd_18ef_sbn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_20/bd_18ef_m00s2a_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_21/bd_18ef_m00arn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_22/bd_18ef_m00rn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_23/bd_18ef_m00awn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_24/bd_18ef_m00wn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_25/bd_18ef_m00bn_0_ooc.xdc

# IP: D:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/design_fft_axi_smc_0.xci
# IP: The module: 'design_fft_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/bd_18ef.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_0/bd_18ef_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_1/bd_18ef_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_2/bd_18ef_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_3/bd_18ef_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_4/bd_18ef_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_5/bd_18ef_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_6/bd_18ef_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_7/bd_18ef_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_8/bd_18ef_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_9/bd_18ef_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_10/bd_18ef_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_11/bd_18ef_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_12/bd_18ef_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_13/bd_18ef_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_14/bd_18ef_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_15/bd_18ef_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_16/bd_18ef_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_17/bd_18ef_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_18/bd_18ef_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_19/bd_18ef_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_20/bd_18ef_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_21/bd_18ef_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_22/bd_18ef_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_23/bd_18ef_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_24/bd_18ef_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_25/bd_18ef_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_26/bd_18ef_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_fft_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_1/bd_18ef_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_1/bd_18ef_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_2/bd_18ef_arsw_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_3/bd_18ef_rsw_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_4/bd_18ef_awsw_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_5/bd_18ef_wsw_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_6/bd_18ef_bsw_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_10/bd_18ef_s00a2s_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_11/bd_18ef_sarn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_12/bd_18ef_srn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_16/bd_18ef_s01a2s_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_17/bd_18ef_sawn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_18/bd_18ef_swn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_19/bd_18ef_sbn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_20/bd_18ef_m00s2a_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_21/bd_18ef_m00arn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_22/bd_18ef_m00rn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_23/bd_18ef_m00awn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_24/bd_18ef_m00wn_0_ooc.xdc

# XDC: d:/Drive_D/ELD2023/Lab10_HW/Lab10_HW.srcs/sources_1/bd/design_fft/ip/design_fft_axi_smc_0/bd_0/ip/ip_25/bd_18ef_m00bn_0_ooc.xdc
