# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/ELD2023/Lab4_HW/Lab4_HW.cache/wt [current_project]
set_property parent.project_path F:/ELD2023/Lab4_HW/Lab4_HW.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.1 [current_project]
set_property ip_output_repo f:/ELD2023/Lab4_HW/Lab4_HW.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/ELD2023/Lab4_HW/Lab4_HW.srcs/sources_1/imports/sources_1/new/FSM_moore_1101.v
  F:/ELD2023/Lab4_HW/Lab4_HW.srcs/sources_1/imports/sources_1/new/PB_clock.v
  F:/ELD2023/Lab4_HW/Lab4_HW.srcs/sources_1/imports/sources_1/new/Top_fsm.v
  F:/ELD2023/Lab4_HW/Lab4_HW.srcs/sources_1/imports/sources_1/imports/new/clk_div_rtl.v
  F:/ELD2023/Lab4_HW/Lab4_HW.srcs/sources_1/imports/sources_1/new/Vio_wrapper.v
}
read_ip -quiet f:/ELD2023/Lab4_HW/Lab4_HW.srcs/sources_1/ip/clk_cmt/clk_cmt.xci
set_property used_in_implementation false [get_files -all f:/ELD2023/Lab4_HW/Lab4_HW.srcs/sources_1/ip/clk_cmt/clk_cmt_board.xdc]
set_property used_in_implementation false [get_files -all f:/ELD2023/Lab4_HW/Lab4_HW.srcs/sources_1/ip/clk_cmt/clk_cmt.xdc]
set_property used_in_implementation false [get_files -all f:/ELD2023/Lab4_HW/Lab4_HW.srcs/sources_1/ip/clk_cmt/clk_cmt_ooc.xdc]

read_ip -quiet f:/ELD2023/Lab4_HW/Lab4_HW.srcs/sources_1/ip/vio_fs3/vio_fs3.xci
set_property used_in_implementation false [get_files -all f:/ELD2023/Lab4_HW/Lab4_HW.srcs/sources_1/ip/vio_fs3/vio_fs3.xdc]
set_property used_in_implementation false [get_files -all f:/ELD2023/Lab4_HW/Lab4_HW.srcs/sources_1/ip/vio_fs3/vio_fs3_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/ELD2023/Lab4_HW/Lab4_HW.srcs/constrs_1/imports/new/Zedboard.xdc
set_property used_in_implementation false [get_files F:/ELD2023/Lab4_HW/Lab4_HW.srcs/constrs_1/imports/new/Zedboard.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Vio_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Vio_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Vio_wrapper_utilization_synth.rpt -pb Vio_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
