# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Drive D/ELD2023/Lab7_HW_1/Lab7_HW_1.srcs/sources_1/ip/xfft_32/xfft_32.xci
# IP: The module: 'xfft_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Drive D/ELD2023/Lab7_HW_1/Lab7_HW_1.srcs/sources_1/ip/xfft_32/xfft_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Drive D/ELD2023/Lab7_HW_1/Lab7_HW_1.srcs/sources_1/ip/xfft_32/xfft_32.xci
# IP: The module: 'xfft_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Drive D/ELD2023/Lab7_HW_1/Lab7_HW_1.srcs/sources_1/ip/xfft_32/xfft_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
