@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Nov 01 16:10:12 +0530 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim arith_test_behav -key {Behavioral:sim_1:Functional:arith_test} -tclbatch arith_test.tcl -view D:/Drive_D/ELD2023/Lab_7_HW_2/arith_test_behav.wcfg -log simulate.log"
call xsim  arith_test_behav -key {Behavioral:sim_1:Functional:arith_test} -tclbatch arith_test.tcl -view D:/Drive_D/ELD2023/Lab_7_HW_2/arith_test_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
