# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Drive D/ELD2023/Lab6_HW_Approach/Lab6_HW_Approach.srcs/sources_1/ip/FP_recip/FP_recip.xci
# IP: The module: 'FP_recip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Drive D/ELD2023/Lab6_HW_Approach/Lab6_HW_Approach.srcs/sources_1/ip/FP_recip/FP_recip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_recip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Drive D/ELD2023/Lab6_HW_Approach/Lab6_HW_Approach.srcs/sources_1/ip/FP_recip/FP_recip.xci
# IP: The module: 'FP_recip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Drive D/ELD2023/Lab6_HW_Approach/Lab6_HW_Approach.srcs/sources_1/ip/FP_recip/FP_recip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_recip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
