# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Drive_D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.cache/wt [current_project]
set_property parent.project_path D:/Drive_D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.2 [current_project]
set_property ip_output_repo d:/Drive_D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Drive_D/ELD2023/Lab6_HW_Approach/Lab6_HW_Approach.srcs/sources_1/new/Top_arith.v
read_ip -quiet D:/Drive_D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.srcs/sources_1/ip/floating_point_div/floating_point_div.xci
set_property used_in_implementation false [get_files -all d:/Drive_D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.srcs/sources_1/ip/floating_point_div/floating_point_div_ooc.xdc]

read_ip -quiet D:/Drive_D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.srcs/sources_1/ip/floating_point_log/floating_point_log.xci
set_property used_in_implementation false [get_files -all d:/Drive_D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.srcs/sources_1/ip/floating_point_log/floating_point_log_ooc.xdc]

read_ip -quiet D:/Drive_D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.srcs/sources_1/ip/floating_point_multiply/floating_point_multiply.xci
set_property used_in_implementation false [get_files -all d:/Drive_D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.srcs/sources_1/ip/floating_point_multiply/floating_point_multiply_ooc.xdc]

read_ip -quiet D:/Drive_D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.srcs/sources_1/ip/floating_point_sqrt/floating_point_sqrt.xci
set_property used_in_implementation false [get_files -all d:/Drive_D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.srcs/sources_1/ip/floating_point_sqrt/floating_point_sqrt_ooc.xdc]

read_ip -quiet D:/Drive_D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.srcs/sources_1/ip/floating_point_add/floating_point_add.xci
set_property used_in_implementation false [get_files -all d:/Drive_D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.srcs/sources_1/ip/floating_point_add/floating_point_add_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top_arith -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_arith.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_arith_utilization_synth.rpt -pb Top_arith_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
