# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Drive D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.srcs/sources_1/ip/floating_point_sqrt/floating_point_sqrt.xci
# IP: The module: 'floating_point_sqrt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Drive D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.srcs/sources_1/ip/floating_point_sqrt/floating_point_sqrt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_sqrt'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Drive D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.srcs/sources_1/ip/floating_point_sqrt/floating_point_sqrt.xci
# IP: The module: 'floating_point_sqrt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Drive D/ELD2023/Lab_7_HW_2/Lab_7_HW_2.srcs/sources_1/ip/floating_point_sqrt/floating_point_sqrt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_sqrt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
