# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Drive D/ELD2023/Lab6_HW/Lab6_HW.srcs/sources_1/ip/FP_log/FP_log.xci
# IP: The module: 'FP_log' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Drive D/ELD2023/Lab6_HW/Lab6_HW.srcs/sources_1/ip/FP_log/FP_log_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_log'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Drive D/ELD2023/Lab6_HW/Lab6_HW.srcs/sources_1/ip/FP_log/FP_log.xci
# IP: The module: 'FP_log' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Drive D/ELD2023/Lab6_HW/Lab6_HW.srcs/sources_1/ip/FP_log/FP_log_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_log'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
